WITH
CTE_SUPER_CADASTRO AS (
SELECT
   CAST(CAST(T1.NUM_CPFCNPJ AS BIGINT) AS STRING) AS NUM_CPFCNPJ
,CAST(CAST(T1.NUM_CPFCNPJ14 AS BIGINT) AS STRING) AS NUM_CPFCNPJ14                                   /*ADICIONADO POR MIM: MICHAEL*/
,T1.NUM_AGENCIA
,T1.NUM_CONTA
,T1.NUM_CONTA_DAC
,T1.COD_TIPO_PESSOA
,T1.DES_NEGOCIO
,T1.DAT_CONTA_ABERTURA_EFETIVA
,T1.DES_CONTA_STATUS
,CASE WHEN T1.DES_CONTA_STATUS IN ('CONTA ATIVA - RE','CONTA ATIVA','CONTA TEMPORARIAMENTE INATIVA 35 DIAS','CONTA TEMPORARIAMENTE INATIVA 35 DIAS - RE') THEN 1 ELSE 0 END AS FLAG_CONTA_ATIVA
,T1.DES_SEGMENTACAO
,T1.DES_SUB_SEGMENTACAO
,T1.DES_CHAVE_SEGMENTO
,T1.DES_CONTA_SUB_TIPO
FROM TBL_BUPJ_DE_CADASTRO_SUPER_CADASTRO T1
WHERE T1.NUM_CONTA IS NOT NULL
 
    ), CTE_SOCIOS AS (
SELECT DISTINCT CAST(CAST(TRIM(T1.NUM_CNPJ_ESTB) AS BIGINT) AS STRING) AS CNPJ
               ,CAST(CAST(SUBSTRING(TRIM(T1.NUM_CNPJ_ESTB),1,8) AS BIGINT) AS STRING) AS NUM_CNPJ_RAIZ
               ,1 AS NUM_CNPJ_FILIAL
               ,T1.COD_TIPO_PESS_CTTO AS COD_TIPO_PESS
               ,T1.NOM_SCIO_EMPR
               ,'XXXX' AS DES_CRGO_FUNC_SCIO
               ,T1.PCT_PARP_SCIO
               ,SUBSTRING(T1.NUM_DOCM_CPF_CNPJ_SCIO,1,9) AS NUM_MATRIZ_SOCIO
               ,SUBSTRING(T1.NUM_DOCM_CPF_CNPJ_SCIO,1,9) AS CPF
               ,SUBSTRING(T1.NUM_DOCM_CPF_CNPJ_SCIO,1,9) AS NUM_CPF
               ,T1.NUM_DOCM_CPF_CNPJ_SCIO AS _CPF1_
               ,T1.NOM_SCIO_EMPR AS NOM_COMPLETO
               ,'9999-99-99' AS DAT_NASCIMENTO
               ,'XXXX' AS CIDADE
               ,'XX' AS ESTADO
               ,MAX(DAT_HOR_INCU_RGTO) AS DAT_HOR_INCU_RGTO
             
FROM  TBNB3018_MELH_QUAD_SCTO T1
GROUP BY
                CAST(CAST(TRIM(T1.NUM_CNPJ_ESTB) AS BIGINT) AS STRING)
               ,CAST(CAST(SUBSTRING(TRIM(T1.NUM_CNPJ_ESTB),1,8) AS BIGINT) AS STRING)
               ,T1.COD_TIPO_PESS_CTTO
               ,T1.NOM_SCIO_EMPR
               ,T1.PCT_PARP_SCIO
               ,SUBSTRING(T1.NUM_DOCM_CPF_CNPJ_SCIO,1,9)
               ,SUBSTRING(T1.NUM_DOCM_CPF_CNPJ_SCIO,1,9)
               ,SUBSTRING(T1.NUM_DOCM_CPF_CNPJ_SCIO,1,9)
               ,T1.NUM_DOCM_CPF_CNPJ_SCIO
               ,T1.NOM_SCIO_EMPR  
), CTE_MV_TOTAL AS (
         SELECT T1.AGENCIA
               ,T1.CONTA
               /*,CAST(T1.CPF_9 AS BIGINT) AS CPF_9*/
               ,CASE LENGTH(CAST(T1.CPF_9 AS STRING))
WHEN 1 THEN '00000000'||CAST(T1.CPF_9 AS STRING)
WHEN 2 THEN  '0000000'||CAST(T1.CPF_9 AS STRING)
WHEN 3 THEN   '000000'||CAST(T1.CPF_9 AS STRING)
WHEN 4 THEN    '00000'||CAST(T1.CPF_9 AS STRING)
WHEN 5 THEN     '0000'||CAST(T1.CPF_9 AS STRING)
WHEN 6 THEN      '000'||CAST(T1.CPF_9 AS STRING)
WHEN 7 THEN       '00'||CAST(T1.CPF_9 AS STRING)
WHEN 8 THEN        '0'||CAST(T1.CPF_9 AS STRING)
ELSE CAST(T1.CPF_9 AS STRING) END AS CPF_9
               ,T1.CPFCNPJ                                 /*ADICIONADO POR MIM: MICHAEL*/
               ,T1.FLAG_CONTA
               ,T1.NIVEL_IP_ATUAL
               ,T1.PONTUACAO_IP_ATUAL
               ,T1.ANOMES_OPTIN_NUM
               ,T1.ANOMES
         FROM  TBL_PRICING_DE_ENGAJAMENTO_PUBLICO_MINHAS_VANTAGENS T1

/*------------------------------------------------------------------ CTE PARA APURACAO --------------------------------------------------------------------*/    
  ), CTE_SOCIOS2 AS (
         SELECT T1.CNPJ
               ,T1.NUM_CNPJ_RAIZ
               ,T1.NUM_CNPJ_FILIAL
               ,T1.COD_TIPO_PESS
               ,T1.NOM_SCIO_EMPR
               ,T1.DES_CRGO_FUNC_SCIO
               ,T1.NUM_MATRIZ_SOCIO
               ,T1.PCT_PARP_SCIO
               ,SUM(COALESCE(T1.PCT_PARP_SCIO,0)) AS SUM_PCT_PARP_SCIO
               ,SUM(T1.PCT_PARP_SCIO) AS SUM_PCT_PARP_SCIO_
               ,CASE
           WHEN SUM(COALESCE(T1.PCT_PARP_SCIO,0)) = 0 THEN 10000/COUNT(DISTINCT NUM_MATRIZ_SOCIO)
                    /*QUANDO FOR IGUAL A ZERO DIVIDE POR IGUAL PARA TODOS OS SOCIOS*/
            WHEN SUM(COALESCE(T1.PCT_PARP_SCIO,0)) > 0 AND COALESCE(PCT_PARP_SCIO,0) = 0 THEN -9999
           ELSE COALESCE(PCT_PARP_SCIO,0)
             END AS PCT_PARP_SCIO_AJST
/*MARCA O SÓCIO QUE ESTIVER COM PARTICIPACAO ZERADA, E SOCIOS QUE COMPOEM OS 100% DO QUADRO*/
               ,T1.CPF
               ,T1.NUM_CPF
               ,_CPF1_
               ,T1.NOM_COMPLETO
               ,T1.DAT_NASCIMENTO
               ,T1.CIDADE
               ,T1.ESTADO
               ,T1.dat_hor_incu_rgto
         FROM  CTE_SOCIOS T1
         WHERE T1.PCT_PARP_SCIO IS NOT NULL OR T1.PCT_PARP_SCIO > 0
         GROUP BY T1.CNPJ
                 ,T1.NUM_CNPJ_RAIZ
                 ,T1.NUM_CNPJ_FILIAL
                 ,T1.COD_TIPO_PESS
                 ,T1.NOM_SCIO_EMPR
                 ,T1.DES_CRGO_FUNC_SCIO
                 ,T1.NUM_MATRIZ_SOCIO
                 ,T1.PCT_PARP_SCIO
                 ,T1.CPF
                 ,T1.NUM_CPF
                 ,T1._CPF1_
                 ,T1.NOM_COMPLETO
                 ,T1.DAT_NASCIMENTO
                 ,T1.CIDADE
                 ,T1.ESTADO
                 ,T1.dat_hor_incu_rgto

   ), CTE_SOCIOS3 AS (
SELECT DISTINCT
CNPJ
,NUM_CNPJ_RAIZ
,NUM_CNPJ_FILIAL
,COD_TIPO_PESS
,NOM_SCIO_EMPR
,DES_CRGO_FUNC_SCIO
,NUM_MATRIZ_SOCIO
,COUNT(DISTINCT NUM_MATRIZ_SOCIO) AS QTD_SOCIOS
,PCT_PARP_SCIO
,SUM_PCT_PARP_SCIO
,PCT_PARP_SCIO_AJST
,LPAD(CPF,9,'0') AS CPF
,NUM_CPF
,_CPF1_
,NOM_COMPLETO
,DAT_NASCIMENTO
,CIDADE
,ESTADO
,dat_hor_incu_rgto
,RANK() OVER( PARTITION BY _CPF1_,CNPJ ORDER BY dat_hor_incu_rgto ASC) AS ROW_CPF
FROM CTE_SOCIOS2
WHERE PCT_PARP_SCIO_AJST >= 0
/*FILTRA MANTENDO SOMENTE OS SÓCIOS COM PARTICIPAÇÃO MAIOR QUE ZERO*/
GROUP BY
 CNPJ
,NUM_CNPJ_RAIZ
,NUM_CNPJ_FILIAL
,COD_TIPO_PESS
,NOM_SCIO_EMPR
,DES_CRGO_FUNC_SCIO
,NUM_MATRIZ_SOCIO
,PCT_PARP_SCIO
,SUM_PCT_PARP_SCIO
,PCT_PARP_SCIO_AJST
,CPF
,NUM_CPF
,_CPF1_
,NOM_COMPLETO
,DAT_NASCIMENTO
,CIDADE
,ESTADO
,dat_hor_incu_rgto
),CTE_SOCIOS3_STG AS (
SELECT * FROM CTE_SOCIOS3 WHERE ROW_CPF = 1
), CTE_CONSULT AS (
SELECT DISTINCT
   
A.NUM_CPFCNPJ AS CNPJBAS
,A.NUM_CPFCNPJ14
,A.NUM_AGENCIA AS NUM_AGENCIA_PJ
,A.NUM_CONTA AS NUM_CONTA_PJ
,A.NUM_CONTA_DAC
,CAST(A.NUM_AGENCIA AS STRING)||CAST(A.NUM_CONTA AS STRING) AS AGENCIA_CONTA_PJ
,A.COD_TIPO_PESSOA
,A.DES_NEGOCIO
,A.DES_CONTA_STATUS AS STATUS_CONTA_PJ
,A.FLAG_CONTA_ATIVA
,A.DES_SEGMENTACAO AS SEGMENTO_PJ
,B.CPF
,B.NOM_COMPLETO
,B.PCT_PARP_SCIO/100 AS PCT_SOCIO
,B.DES_CRGO_FUNC_SCIO
,C.AGENCIA AS NUM_AGENCIA_PF
,C.CONTA AS NUM_CONTA_PF
,CAST(C.AGENCIA AS STRING)||CAST(C.CONTA AS STRING) AS AGENCIA_CONTA_PF
,C.FLAG_CONTA AS FLAG_CONTA_PF
,C.NIVEL_IP_ATUAL
,C.PONTUACAO_IP_ATUAL
,CASE WHEN COALESCE(CAST(C.ANOMES_OPTIN_NUM AS BIGINT),0) = 0 THEN 0 ELSE 1 END AS FLAG_OPTIN
FROM CTE_SUPER_CADASTRO AS A
LEFT JOIN CTE_SOCIOS3_STG AS B ON  CAST(A.NUM_CPFCNPJ AS BIGINT) = CAST(B.NUM_CNPJ_RAIZ AS BIGINT) AND CAST(A.NUM_CPFCNPJ14 AS BIGINT) = CAST(B.CNPJ AS BIGINT)
LEFT JOIN CTE_MV_TOTAL /* FALAR COM O ALAN PARA COPIAR NA OUT001*/ AS C ON CAST(B.CPF AS BIGINT) = CAST(C.CPF_9 AS BIGINT)
WHERE   C.CPF_9 IS NOT NULL/*COM CPF_9 IS NOT MISSING FILTRAMOS APENAS OS CPFS QUE ESTÃO NA BASE DO MV PERSONNALITE*/
), CTE_CONSULT_2 AS (
SELECT DISTINCT
A.CNPJBAS
,COUNT(DISTINCT A.AGENCIA_CONTA_PJ) AS QTD_CONTAS
,A.NUM_AGENCIA_PJ
,A.NUM_CONTA_PJ
,A.NUM_CONTA_DAC
,A.AGENCIA_CONTA_PJ
,A.COD_TIPO_PESSOA
,A.DES_NEGOCIO
,A.STATUS_CONTA_PJ
,A.FLAG_CONTA_ATIVA
,A.SEGMENTO_PJ
,A.CPF AS CPF
,A.NOM_COMPLETO AS NOME_SOCIO
,A.PCT_SOCIO
,A.DES_CRGO_FUNC_SCIO AS DES_CRGO_FUNC_SCIO
,A.NUM_AGENCIA_PF
,A.NUM_CONTA_PF
,A.AGENCIA_CONTA_PF
,A.FLAG_CONTA_PF
,A.NIVEL_IP_ATUAL
,A.PONTUACAO_IP_ATUAL
,A.FLAG_OPTIN
FROM CTE_CONSULT AS A
GROUP BY
A.CNPJBAS
,A.NUM_AGENCIA_PJ
,A.NUM_CONTA_PJ
,A.NUM_CONTA_DAC
,A.AGENCIA_CONTA_PJ
,A.COD_TIPO_PESSOA
,A.DES_NEGOCIO
,A.STATUS_CONTA_PJ
,A.FLAG_CONTA_ATIVA
,A.SEGMENTO_PJ
,A.CPF
,A.NOM_COMPLETO
,A.PCT_SOCIO
,A.DES_CRGO_FUNC_SCIO
,A.NUM_AGENCIA_PF
,A.NUM_CONTA_PF
,A.AGENCIA_CONTA_PF
,A.FLAG_CONTA_PF
,A.NIVEL_IP_ATUAL
,A.PONTUACAO_IP_ATUAL
,A.FLAG_OPTIN
), CTE_CONSULT_3 AS (

     SELECT
A.CNPJBAS
,A.QTD_CONTAS
,A.NUM_AGENCIA_PJ
,A.NUM_CONTA_PJ
,A.NUM_CONTA_DAC
,A.AGENCIA_CONTA_PJ
,COUNT(DISTINCT A.CPF) AS QTD_SOCIOS_IP
,A.COD_TIPO_PESSOA
,A.DES_NEGOCIO
,A.STATUS_CONTA_PJ
,A.FLAG_CONTA_ATIVA
,A.SEGMENTO_PJ
,A.CPF
,A.NOME_SOCIO
,A.PCT_SOCIO
,A.DES_CRGO_FUNC_SCIO
,A.NUM_AGENCIA_PF
,A.NUM_CONTA_PF
,A.AGENCIA_CONTA_PF
,A.FLAG_CONTA_PF
,A.NIVEL_IP_ATUAL
,A.PONTUACAO_IP_ATUAL
,A.FLAG_OPTIN
FROM CTE_CONSULT_2 AS A
GROUP BY
A.CNPJBAS
,A.QTD_CONTAS
,A.NUM_AGENCIA_PJ
,A.NUM_CONTA_PJ
,A.NUM_CONTA_DAC
,A.AGENCIA_CONTA_PJ
,A.COD_TIPO_PESSOA
,A.DES_NEGOCIO
,A.STATUS_CONTA_PJ
,A.FLAG_CONTA_ATIVA
,A.SEGMENTO_PJ
,A.CPF
,A.NOME_SOCIO
,A.PCT_SOCIO
,A.DES_CRGO_FUNC_SCIO
,A.NUM_AGENCIA_PF
,A.NUM_CONTA_PF
,A.AGENCIA_CONTA_PF
,A.FLAG_CONTA_PF
,A.NIVEL_IP_ATUAL
,A.PONTUACAO_IP_ATUAL
,A.FLAG_OPTIN
),CTE_BASE_PREP_ISENCAO_MV AS  (
        SELECT   *,
    CASE WHEN FLAG_CONTA_ATIVA = 1
    AND DES_NEGOCIO = 'VAREJO'
    AND FLAG_OPTIN = 1
    AND NIVEL_IP_ATUAL >= 4
    THEN 'S' ELSE 'N'
    END AS ELEGIBILIDADE_POTENCIAL
    ,ROW_NUMBER() OVER(
      PARTITION BY AGENCIA_CONTA_PJ
      ORDER BY NUM_CONTA_PJ ASC) AS ROW_AGENCIA
    FROM CTE_CONSULT_3

), CTE_BASE_POTENCIAL_MV_STG AS  (
    SELECT DISTINCT
T1.CNPJBAS
,T1.QTD_CONTAS
,T1.NUM_AGENCIA_PJ
,T1.NUM_CONTA_PJ
,T1.NUM_CONTA_DAC
,T1.AGENCIA_CONTA_PJ
,T1.QTD_SOCIOS_IP
,T1.COD_TIPO_PESSOA
,T1.DES_NEGOCIO
,T1.STATUS_CONTA_PJ
,T1.FLAG_CONTA_ATIVA
,T1.SEGMENTO_PJ
,T1.FLAG_OPTIN
,T1.NIVEL_IP_ATUAL
,RANK() OVER(
  PARTITION BY CNPJBAS,NUM_AGENCIA_PJ,NUM_CONTA_PJ
  ORDER BY  T1.NIVEL_IP_ATUAL DESC) AS ROWN_IP
FROM CTE_BASE_PREP_ISENCAO_MV AS T1
WHERE
T1.FLAG_CONTA_ATIVA = 1  
AND T1.DES_NEGOCIO = 'VAREJO'  
AND T1.FLAG_OPTIN = 1
AND T1.NIVEL_IP_ATUAL  >= 4
/*--------------------------------------04 - MARCA PACOTE----------------------*/

),CTE_BASE_POTENCIAL_MV AS (
SELECT
T1.CNPJBAS
,T1.QTD_CONTAS
,T1.NUM_AGENCIA_PJ
,T1.NUM_CONTA_PJ
,T1.NUM_CONTA_DAC
,T1.AGENCIA_CONTA_PJ
,T1.QTD_SOCIOS_IP
,T1.COD_TIPO_PESSOA
,T1.DES_NEGOCIO
,T1.STATUS_CONTA_PJ
,T1.FLAG_CONTA_ATIVA
,T1.SEGMENTO_PJ
,T1.FLAG_OPTIN
,T1.NIVEL_IP_ATUAL

FROM CTE_BASE_POTENCIAL_MV_STG T1
WHERE
ROWN_IP = 1
), CTE_PACOTES_ATIVOS_STG AS (

SELECT
AGENCIA
,CONTA
/*/,PACOTE_ATUAL AS COD_DO_PACOTE*/
   ,COD_DO_PACOTE
,DAC
,DATA_INICIO
,DATA_FIM
,DATA_CONTRATA
/* ,CASE
WHEN LENGTH(CAST(DATA_CONTRAT AS STRING)) = 7 THEN '0'||CAST(DATA_CONTRAT AS STRING)
ELSE CAST(DATA_CONTRAT AS STRING) END AS DT_CONTRATA*/
/* ,CASE
WHEN LENGTH(CAST(DATA_INICIO AS STRING)) = 7 THEN '0'||CAST(DATA_INICIO AS STRING)
ELSE CAST(DATA_INICIO AS STRING) END AS  DT_INCIO*/
/* ,CASE
WHEN LENGTH(CAST(DATA_FIM AS STRING)) = 7 THEN '0'||CAST(DATA_FIM AS STRING)
ELSE CAST(DATA_FIM AS STRING) END AS  DT_FIM*/
,CAST(CURRENT_DATE AS DATE) AS VIGENCIA_PACOTE_MES
FROM TBL_PRICING_DE_CADASTRO_BASE_PRODUCAO  A
/*WHERE MEIO <>'SAIU PACOTE'*/
), CTE_PACOTES_ATIVOS AS (

SELECT
AGENCIA
,CONTA
,COD_DO_PACOTE
,DAC
/* ,CAST(SUBSTRING(CAST(DATA_CONTRATA AS STRING), 7, 4)||'-'||SUBSTRING(CAST(DATA_CONTRATA AS STRING), 4, 2)||'-'||SUBSTRING(CAST(DATA_CONTRATA AS STRING), 1, 2) AS DATE) AS DT_CONTRATA*/
    ,CAST(DATA_CONTRATA  AS DATE) AS  DT_CONTRATA
/*,CAST(SUBSTRING(CAST(DATA_INICIO AS STRING), 7, 4)||'-'||SUBSTRING(CAST(DATA_INICIO AS STRING), 4, 2)||'-'||SUBSTRING(CAST(DATA_INICIO AS STRING), 1, 2) AS DATE) AS DT_INCIO*/
,CAST(DATA_INICIO  AS DATE) AS   DT_INCIO
/*,CAST(SUBSTRING(CAST(DATA_FIM AS STRING), 7, 4)||'-'||SUBSTRING(CAST(DATA_FIM AS STRING), 4, 2)||'-'||SUBSTRING(CAST(DATA_FIM AS STRING), 1, 2) AS DATE) AS DT_FIM*/
,CAST(DATA_FIM AS DATE) AS DT_FIM
,VIGENCIA_PACOTE_MES
FROM CTE_PACOTES_ATIVOS_STG A
WHERE
VIGENCIA_PACOTE_MES BETWEEN
CAST(DATA_INICIO AS DATE) AND CAST(DATA_FIM AS DATE)
),CTE_PACOTE_MARCADO_STG AS  (
SELECT
T1.*,
T2.COD_DO_PACOTE,
CASE
WHEN T2.COD_DO_PACOTE IN ('J6', 'J7', 'J8') THEN 'ADAPT'
WHEN T2.COD_DO_PACOTE IS NULL THEN 'SEM PACOTE'
ELSE 'CONTA CERTA'
END AS DESCR_PACOTE
FROM  CTE_BASE_POTENCIAL_MV T1
LEFT JOIN CTE_PACOTES_ATIVOS T2 ON T1.NUM_AGENCIA_PJ = T2.AGENCIA AND T1.NUM_CONTA_PJ = T2.CONTA
),CTE_PACOTE_MARCADO AS  (
SELECT
T1.*,
CASE
WHEN T1.NUM_CONTA_PJ IS NULL THEN 'CONTA NÃO ENCONTRADA'
WHEN DESCR_PACOTE = 'SEM PACOTE' THEN 'CONTA SEM PACOTE'
WHEN DESCR_PACOTE = 'ADAPT' THEN 'ISENTAR'
ELSE DESCR_PACOTE
END
AS STATUS_ISENTAR
FROM  CTE_PACOTE_MARCADO_STG T1
), CTE_BASE_FINAL_MV AS (
SELECT
*
   FROM CTE_PACOTE_MARCADO
 
 
   /*-------------------------05 - DEFINE VIGÊNCIA E PERCENTUAL--------------------------------*/
   
 ),CTE_VIGENCIA_ISENCAO AS  (
SELECT
T1.*,
DATE_TRUNC('MONTH', CURRENT_DATE) AS DATA_INI,
--'11/'||CAST(MONTH(add_months(CURRENT_DATE, 1)) AS STRING)||'/'||CAST(YEAR(add_months(CURRENT_DATE, 1))  AS STRING) AS DATA_FIM,
'11/'||CAST(MONTH(ADD_MONTHS(CURRENT_DATE(),1)) AS STRING)||'/'||CAST(YEAR(ADD_MONTHS(CURRENT_DATE(),1))  AS STRING) AS DATA_FIM,
'10000' AS PERCENTUAL,
'0126  - MINHAS VANGATAGENS PF' AS DESCR_ISENC,
'XXXXXXXX' AS FUNCIONAL
FROM CTE_PACOTE_MARCADO T1

/*-------------------------06 - GUARDA HISTORICO----------------------------*/

),CTE_ADP_ISENC_MINH_VANT AS (
SELECT
T1.CNPJBAS,
CAST(T1.NUM_AGENCIA_PJ AS STRING) AS COD_AGENCIA,
CAST(T1.NUM_CONTA_PJ  AS STRING) AS COD_CONTA,
CAST(T1.NUM_CONTA_DAC AS STRING) AS COD_DAC,
T1.COD_DO_PACOTE,
T1.STATUS_ISENTAR,
CAST(SUBSTR(T1.DATA_FIM, 7, 4)||'-'||SUBSTR(T1.DATA_FIM, 4, 2)||'-'||SUBSTR(T1.DATA_FIM, 1, 2) AS DATE) AS DATA_FIM_ISENC,
   T1.DATA_FIM,
   1 AS PERCENTUAL,
T1.DESCR_ISENC,
T1.FUNCIONAL
FROM CTE_VIGENCIA_ISENCAO T1

/*-------------------------------------------   08 - LAYOUT   -------------------------------------------------*/
),CTE_ISENCAO_LAYOUT_STG AS (
SELECT
'5' AS COD_TIPO_ISENC,
LPAD(CAST(COD_AGENCIA AS STRING),4,'0') AS COD_AGENCIA,
LPAD(CAST(COD_CONTA AS STRING),7,'0') AS  COD_CONTA,
COD_DAC,
'01/'||CAST(MONTH(CURRENT_DATE) AS STRING)||'/'||CAST(YEAR(CURRENT_DATE) AS STRING) AS DATA_INI,
CAST(DAY(DATA_FIM_ISENC) AS STRING)||'/'||CAST(MONTH(DATA_FIM_ISENC) AS STRING)||'/'||CAST(YEAR(DATA_FIM_ISENC) AS STRING) AS DATA_FIM,
CONCAT(COD_DO_PACOTE, '     ', '00000000000000000000010000') AS GAMBI,
DESCR_ISENC,
'XXXXXXXXX' AS FUNCIONAL,
CAST(NULL AS STRING) AS DATA_INI2_,
CAST('00000000' AS STRING) AS DATA_INI3_,
CAST(NULL AS STRING) AS DATA_FIM2_,
CAST('00000000' AS STRING) AS DATA_FIM3_
FROM CTE_ADP_ISENC_MINH_VANT
WHERE COD_DO_PACOTE IN ('J6', 'J7', 'J8') AND STATUS_ISENTAR = 'ISENTAR'
),CTE_ISENCAO_LAYOUT AS (
SELECT
A.*,
CASE
WHEN DATA_INI <> '00000000' THEN DATA_INI
ELSE DATA_INI3_
END AS DT_INI2,
CASE
WHEN DATA_FIM <> '00000000' THEN DATA_FIM
ELSE  DATA_FIM3_
END AS DATA_FIM2
FROM CTE_ISENCAO_LAYOUT_STG AS A
),CTE_ISENCAO_MV AS (
SELECT * FROM CTE_ISENCAO_LAYOUT
),CTE_LAYOUT AS (

SELECT
'I' AS IR,
COD_TIPO_ISENC AS TIPO_ISENC,
COD_AGENCIA AS AGENCIA,
COD_CONTA AS CONTA,
COD_DAC AS DAC,
REPLACE(DT_INI2,'/','') AS DT_INI2,
REPLACE(DATA_FIM2,'/','') AS DATA_FIM2,
GAMBI AS GAMBI2,
RPAD(DESCR_ISENC,100,' ') AS DESCR_ISENC2,
FUNCIONAL AS FUNCIONAL2,
'0000000' AS ZEROS,
CURRENT_DATE  AS ANOMESDIA
FROM CTE_ISENCAO_MV
) SELECT * FROM CTE_LAYOUT;
